site_name: Codigo de Comercio de Guatemala
pages:
  - Inicio: 'index.md'
  - Titulo Preliminar: 'titulo-preliminar.md'
  - Libro I - Titulo I - Comerciantes:
    - 'Capitulo I': 'libro1/titulo1/capitulo1.md'
    - 'Capitulo II': 'libro1/titulo1/capitulo2.md'
    - 'Capitulo III': 'libro1/titulo1/capitulo3.md'
    - 'Capitulo IV': 'libro1/titulo1/capitulo4.md'
    - 'Capitulo V': 'libro1/titulo1/capitulo5.md'
    - 'Capitulo VI': 'libro1/titulo1/capitulo6.md'
    - 'Capitulo VII': 'libro1/titulo1/capitulo7.md'
    - 'Capitulo VIII': 'libro1/titulo1/capitulo8.md'
    - 'Capitulo IX': 'libro1/titulo1/capitulo9.md'
    - 'Capitulo X': 'libro1/titulo1/capitulo10.md'
    - 'Capitulo XI': 'libro1/titulo1/capitulo11.md'
    - 'Capitulo XII': 'libro1/titulo1/capitulo12.md'
  - Libro I - Titulo II - Auxiliares de los Comerciantes:
    - 'Capitulo I': 'libro1/titulo2/capitulo1.md'
    - 'Capitulo II': 'libro1/titulo2/capitulo2.md'
    - 'Capitulo III': 'libro1/titulo2/capitulo3.md'
    - 'Capitulo IV': 'libro1/titulo2/capitulo4.md'
    - 'Capitulo V': 'libro1/titulo2/capitulo5.md'
  - Libro II - Titulo I - De las obligaciones profesionales de los comerciantes:  
    - 'Capitulo I': 'libro2/titulo1/capitulo1.md'
    - 'Capitulo II': 'libro2/titulo1/capitulo2.md'
    - 'Capitulo III': 'libro2/titulo1/capitulo3.md'
    - 'Capitulo IV': 'libro2/titulo1/capitulo4.md'
  - Libro II - Titulo II - De las proteccion a la libre competencia: 'libro2/titulo2/capitulo1.md'
  - Libro II - Titulo III - De la contabilidad y correspondencia mercantiles:  
    - 'Capitulo I': 'libro2/titulo3/capitulo1.md'
    - 'Capitulo II': 'libro2/titulo3/capitulo2.md'
  - Libro III - Titulo I - De las cosas mercantiles:
    - 'Capitulo I': 'libro3/titulo1/capitulo1.md'
    - 'Capitulo II': 'libro3/titulo1/capitulo2.md'
    - 'Capitulo III': 'libro3/titulo1/capitulo3.md'
    - 'Capitulo IV': 'libro3/titulo1/capitulo4.md'
    - 'Capitulo V': 'libro3/titulo1/capitulo5.md'
    - 'Capitulo VI': 'libro3/titulo1/capitulo6.md'
    - 'Capitulo VII': 'libro3/titulo1/capitulo7.md'

theme: readthedocs